name: automerge
on:
  pull_request:
    types:
      - labeled
      - synchronize
      - edited
      - ready_for_review
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'automerge') || (github.event.status.state == 'success' && !contains(github.event.status.branches.*.name, 'master')) || contains(github.event.pull_request_review.pull_request.labels.*.name, 'automerge')
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@43fd7e11ee532218966343a262f10771b5eff978"
        with:
          args: "--trace"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
