on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Match all tags

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
      TAG: ${{ github.ref }}
      SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - name: Get latest release
        id: get_latest
        run: |
          tag_name=$(curl --silent --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/releases/latest \
          --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --header "content-type: application/json" | jq -r .tag_name)
          echo "::set-output name=tag_name::$tag_name"
      - name: Fetch # required for the changelog to work correctly.
        run: git fetch --all --prune --unshallow
      - name: Checkout master
        run: git checkout master
      - name: Fetch # required for the changelog to work correctly.
        run: git fetch --all --prune --unshallow
      - name: Pull # required for the changelog to work correctly.
        run: git pull --all
      - name: Build Body
        id: build_body
        env:
          FROM_TAG: ${{ steps.get_latest.outputs.tag_name}}
        run: |
          body=$(sh ./.github/workflows/create-release/build-body.sh)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=body::$body"
      - name: Create Release
        id: create_release
        uses: actions/create-release@4d1b6075ce7561b672b8552148edec2f27584fe9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.build_body.outputs.body }}
          draft: true
          prerelease: false
