on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Match all tags

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
      TAG: ${{ github.ref }}
      SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - name: Get latest release
        id: get_latest
        run: |
          release=$(curl --silent --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/releases/latest \
          --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --header "content-type: application/json")
          tag_name=$(echo $release | jq -r .tag_name)
          echo "::set-output name=tag_name::$tag_name"
      - name: Get tag author
        id: get_author
        run: |
          tag=$(curl --silent --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/git/tags/${SHA} \
          --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --header "content-type: application/json")
          echo $tag
          author_name=$(echo $tag | jq -r .tagger.name)
          author_email=$(echo $tag | jq -r .tagger.email)
          echo "::set-output name=author_name::$author_name"
          echo "::set-output name=author_email::$author_email"
      - name: Fetch # required for the changelog to work correctly.
        run: git fetch --all --prune --unshallow
      - name: Fetch tags
        run: git fetch --unshallow origin +refs/tags/*:refs/tags/*
      - name: Checkout master
        run: git checkout master
      - name: Build Body
        id: build_body
        env:
          FROM_TAG: ${{ steps.get_latest.outputs.tag_name }}
          AUTHOR_NAME: ${{ steps.get_author.outputs.author_name }}
          AUTHOR_EMAIL: ${{ steps.get_author.outputs.author_email }}
        run: |
          body=$(sh ./.github/workflows/create-release/build-body.sh)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=body::$body"
      - name: Create Release
        id: create_release
        uses: actions/create-release@4d1b6075ce7561b672b8552148edec2f27584fe9
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.build_body.outputs.body }}
          draft: false
          prerelease: false
