on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repo }}
    steps:
      - name: Checkout tag
        uses: actions/checkout@master
      - name: Checkout master
        uses: actions/checkout@master
        with:
          ref: master
      - name: Build Body
        id: build_body
        run: |
          body=$(sh ./.github/workflows/create-release/build-body.sh)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=body::$body"
      - name: Create Release
        id: create_release
        uses: actions/create-release@4d1b6075ce7561b672b8552148edec2f27584fe9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.build_body.outputs.body }}
          draft: true
          prerelease: false
