on:
  release:
    types: [published]

name: Deploy
jobs:
  dispatch:
    name: Repository Dispatch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Convert metadata.yml to JSON
        id: convert
        run: |
          snap install -y yq
          metadata=$(yq r -j metadata.yml)
          echo "::set-output name=metadata::$metadata"
      - name: Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: gabrieltaylor/app-state
          event-type: deploy-request
          client-payload: '{"data": {"variables": ${{ steps.convert.outputs.metadata }}, "ref": "${{ github.ref }}", "sha": "6aea87e2055878c679a7fcfa5911f8bf1a9b46af"}}'
