on:
  release:
    types: [published]

name: Deploy
jobs:
  deploy:
    name: Repository Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch payload to app-state
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: gabrieltaylor/app-state
          event-type: deploy-request
          client-payload: '{"data": {"service_name": "graphql-service", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}}'
