on:
  release:
    types: [published]

name: Deploy
jobs:
  dispatch:
    name: Repository Dispatch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Convert metadata.yml to JSON
        id: convert
        uses: stefanprodan/kube-tools@v1
        with:
          command: |
            metadata=$(yq r -j metadata.yml)
            echo "::set-output name=metadata::$metadata"
      - name: Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: gabrieltaylor/app-state
          event-type: deploy-request
          client-payload: '{"data": {"service": ${{ steps.convert.outputs.metadata }}, "ref": "${{ github.ref }}", "sha": "070f5f096c6e795361ac11e71441303c8615dee6"}}'
