on:
  release:
    types: [published]

name: Publish release to confluence
jobs:
  publish:
    name: Publish release notes to Confluence
    runs-on: ubuntu-latest
    steps:
      - name: Publish release notes to Confluence
        uses: gabrieltaylor/publish-to-confluence@26f584768b8faa3785d3d152a156232766d7c068
        env:
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
        with:
          type: 'page'
          title: ${{ github.event.name }}
          body: ${{ github.event.body }}
          space: 'RM'
          hostname: 'github-actions-test.atlassian.net'
          username: 'gtaylorruss@thecitybase.com'
