on:
  release:
    types: [published]

name: Publish release to confluence
jobs:
  publish:
    name: Publish release notes to Confluence
    runs-on: ubuntu-latest
    steps:
      - name: Convert markdown to Confluence markup
        id: convert
        uses: gabrieltaylor/convert-markdown-to-confluence-markup@master
        with:
          markdown: ${{ github.event.release.body }}
      - name: Publish to Confluence
        uses: gabrieltaylor/publish-to-confluence@master
        env:
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
        with:
          type: 'page'
          title: ${{ github.event.release.name }}
          body: ${{ steps.convert.outputs.confluence_markup }}
          parent_id: '98319'
          space: 'RM'
          hostname: 'github-actions-test.atlassian.net'
          username: 'gtaylorruss@thecitybase.com'
